_____

<table align="left" width=100%>
    <td>
        <div style="text-align: center;">
          <img src="./../../images/bar.png" alt=""/>
        </div>
    </td>
    <td>
        <p style="text-align: center; font-size:24px;"><b>Introduction to Data Science</b></p>
        <p style="text-align: center; font-size:18px;"><b>Master in Electrical and Computer Engineering</b></p>
        <p style="text-align: center; font-size:14px;"><b>Pedro Cardoso (pcardoso@ualg.pt)</b></p>
    </td>
</table>

_____

# Regular Expressions Draft Solutions in Python

This notebook contains one possible set of solutions for the regex exercises notebook.

## Basic Pattern Matching with `re`

We'll start with simple regex pattern matching.

In [1]:
import re

# Sample text
text = "The rain in Spain stays mainly in the plain."

# Task: Find all words that contain 'ai'
matches = re.findall(r"\w*ai\w*", text)
print("Matches:", matches)

Matches: ['rain', 'Spain', 'mainly', 'plain']

### 📝 Exercise:
- Find all words that start with 's'.
- Find all 5-letter words.
- Find the position of all occurrences of the word "in".

In [3]:
# Find all words that start with 's'
print("Words that start with 's':", re.findall(r"\bs\w*", text, re.IGNORECASE))

# Find all 5-letter words
print("5-letter words:", re.findall(r"\b\w{5}\b", text))

# Find the position of all occurrences of "in"
for match in re.finditer(r"in", text):
    print(f"Match: {match.group()} Start: {match.start()} End: {match.end()}")

Words that start with 's': ['Spain', 'stays']
5-letter words: ['Spain', 'stays', 'plain']
Match: in Start: 6 End: 8
Match: in Start: 9 End: 11
Match: in Start: 15 End: 17
Match: in Start: 26 End: 28
Match: in Start: 31 End: 33
Match: in Start: 41 End: 43

### More Practice:
- Find all words that end with `ain`.
- Find all words that contain the letter `t`.
- Count how many times the substring `ai` appears in the text.
- Replace the word `Spain` with `Portugal` using `re.sub()`.
- Split the sentence into words using `re.split()`.

In [2]:
# Find all words that end with `ain`
print("Words ending with ain:", re.findall(r"\b\w*ain\b", text))

# Find all words that contain the letter `t`
print("Words containing t:", re.findall(r"\b\w*t\w*\b", text, re.IGNORECASE))

# Count how many times `ai` appears
print("Occurrences of ai:", len(re.findall(r"ai", text)))

# Replace Spain with Portugal
print(re.sub(r"\bSpain\b", "Portugal", text))

# Split the sentence into words
print(re.split(r"\W+", text.strip(".")))

Words ending with ain: ['rain', 'Spain', 'plain']
Words containing t: ['The', 'stays', 'the']
Occurrences of ai: 4
The rain in Portugal stays mainly in the plain.
['The', 'rain', 'in', 'Spain', 'stays', 'mainly', 'in', 'the', 'plain']

### `re.finditer()` Exercises:
- Find the start and end positions of all words that contain `ai`.
- Find the positions of all 5-letter words.
- Find the positions of every match of the pattern `\b\w*n\b`.
- Print each match together with its length.

In [5]:
# Find the start and end positions of all words that contain `ai`
for match in re.finditer(r"\b\w*ai\w*\b", text):
    print(f"AI word: {match.group()} Start: {match.start()} End: {match.end()} Length: {len(match.group())}")

# Find the positions of all 5-letter words
for match in re.finditer(r"\b\w{5}\b", text):
    print(f"5-letter word: {match.group()} Start: {match.start()} End: {match.end()} Length: {len(match.group())}")

# Find the positions of words ending with `n`
for match in re.finditer(r"\b\w*n\b", text):
    print(f"Ends with n: {match.group()} Start: {match.start()} End: {match.end()} Length: {len(match.group())}")

AI word: rain Start: 4 End: 8 Length: 4
AI word: Spain Start: 12 End: 17 Length: 5
AI word: mainly Start: 24 End: 30 Length: 6
AI word: plain Start: 38 End: 43 Length: 5
5-letter word: Spain Start: 12 End: 17 Length: 5
5-letter word: stays Start: 18 End: 23 Length: 5
5-letter word: plain Start: 38 End: 43 Length: 5
Ends with n: rain Start: 4 End: 8 Length: 4
Ends with n: in Start: 9 End: 11 Length: 2
Ends with n: Spain Start: 12 End: 17 Length: 5
Ends with n: in Start: 31 End: 33 Length: 2
Ends with n: plain Start: 38 End: 43 Length: 5

## Regular Expressions with `pandas`

Now let's apply regex to a DataFrame column.

In [6]:
import pandas as pd

# Create sample data
df = pd.DataFrame({
    'emails': [
        'alice@example.com', 'bob123@gmail.net', 'charlie99@yahoo.co.uk',
        'no-reply@service.io', 'invalid-email@.com'
    ]
})

# Extract username before '@'
df['username'] = df['emails'].str.extract(r"^([\w.-]+)@")
df

                  emails       username
0      alice@example.com          alice
1       bob123@gmail.net         bob123
2  charlie99@yahoo.co.uk      charlie99
3    no-reply@service.io       no-reply
4     invalid-email@.com  invalid-email

### 📝 Exercises:
- Extract domain names (e.g., `example.com`).
- Find rows with Gmail addresses.
- Flag invalid emails using regex.

In [14]:
# Extract domain names
df["domain"] = df["emails"].str.extract(r"@([A-Za-z0-9.-]+\.[A-Za-z]{2,})$")

# Find rows with Gmail addresses
gmail_rows = df[df["emails"].str.contains(r"@gmail\.", regex=True, na=False)]
print("Gmail addresses:")
display(gmail_rows)

# Flag invalid emails using regex
email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"
df["is_valid"] = df["emails"].str.fullmatch(email_pattern).fillna(False)

df

Gmail addresses:

             emails username     domain  is_valid
1  bob123@gmail.net   bob123  gmail.net      True

                  emails       username       domain  is_valid
0      alice@example.com          alice  example.com      True
1       bob123@gmail.net         bob123    gmail.net      True
2  charlie99@yahoo.co.uk      charlie99  yahoo.co.uk      True
3    no-reply@service.io       no-reply   service.io      True
4     invalid-email@.com  invalid-email          NaN     False

### More `pandas` Regex Exercises:
- Create a new column with the top-level domain only, such as `com`, `net`, `uk`, or `io`.
- Find all emails whose username contains at least one digit.
- Find all emails whose domain starts with the letter `y`.
- Replace every hyphen `-` in the username with an underscore `_`.
- Create a boolean column that marks emails ending in `.com`.

In [17]:
# Create a new column with the top-level domain
df["domain"] = df["emails"].str.extract(r"@([A-Za-z0-9.-]+\.[A-Za-z]{2,})$")
df["tld"] = df["domain"].str.extract(r"([A-Za-z]{2,})$")

# Find all emails whose username contains at least one digit
digit_usernames = df[df["username"].str.contains(r"\d", na=False)]
print("Usernames with digits:")
display(digit_usernames)

# Find all emails whose domain starts with the letter `y`
y_domains = df[df["domain"].str.contains(r"^y", na=False)]
print("Domains that start with y:")
display(y_domains)

# Replace hyphens in the username with underscores
df["username_clean"] = df["username"].str.replace(r"-", "_", regex=True)

# Mark emails ending in `.com`
df["ends_with_com"] = df["emails"].str.contains(r"\.com$", regex=True, na=False)

df

Usernames with digits:

,emails,username,domain,is_valid,tld,username_clean,ends_with_com
1,bob123@gmail.net,bob123,gmail.net,True,net,bob123,False
2,charlie99@yahoo.co.uk,charlie99,yahoo.co.uk,True,uk,charlie99,False

Domains that start with y:

,emails,username,domain,is_valid,tld,username_clean,ends_with_com
2,charlie99@yahoo.co.uk,charlie99,yahoo.co.uk,True,uk,charlie99,False

,emails,username,domain,is_valid,tld,username_clean,ends_with_com
0,alice@example.com,alice,example.com,True,com,alice,True
1,bob123@gmail.net,bob123,gmail.net,True,net,bob123,False
2,charlie99@yahoo.co.uk,charlie99,yahoo.co.uk,True,uk,charlie99,False
3,no-reply@service.io,no-reply,service.io,True,io,no_reply,False
4,invalid-email@.com,invalid-email,NaN,False,NaN,invalid_email,True

## Character Classes, Quantifiers and Groups

Use a new text sample to practice some of the ideas covered in the exploratory notebook.

In [18]:
sample_text = """In 2025, cat, dog, and robot-42 shared room B12.
Another cat slept near code version v1.3 and backup v12.10.
Emails like hello123@test.com and admin@service.io appeared in the logs."""

sample_text

'In 2025, cat, dog, and robot-42 shared room B12.\nAnother cat slept near code version v1.3 and backup v12.10.\nEmails like hello123@test.com and admin@service.io appeared in the logs.'

### New Regex Exercises:
- Find all numbers using `\d+`.
- Find all 3-letter words.
- Find all words that start with `c` and end with `t`.
- Find all version numbers like `v1.3` or `v12.10`.
- Extract all complete email addresses from `sample_text`.
- Find all uppercase letter + digits combinations like `B12`.
- Find all occurrences of either `cat` or `dog` using alternation.
- Build a regex that matches hyphenated words such as `robot-42`.

In [ ]:
# Find all numbers
print("Numbers:", re.findall(r"\d+", sample_text))

# Find all 3-letter words
print("3-letter words:", re.findall(r"\b[a-zA-Z]{3}\b", sample_text))

# Find all words that start with c and end with t
print("Words that start with c and end with t:", re.findall(r"\bc\w*t\b", sample_text))

# Find all version numbers: \bv\d+(?:\.\d+)+\b = v followed by digits, then one or more groups of . followed by digits 
print("Version numbers:", re.findall(r"\bv\d+(?:\.\d+)+\b", sample_text))

# Extract all complete email addresses
print("Emails:", re.findall(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", sample_text))

# Find all uppercase letter + digits combinations
print("Uppercase + digits:", re.findall(r"\b[A-Z]\d+\b", sample_text))

# Find cat or dog: \b(?:cat|dog)\b = non-capturing group for cat or dog, with word boundaries to match whole words only
print("cat or dog:", re.findall(r"\b(?:cat|dog)\b", sample_text))

# Match hyphenated words
print("Hyphenated words:", re.findall(r"\b\w+-\w+\b", sample_text))

Numbers: ['2025', '42', '12', '1', '3', '12', '10', '123']
3-letter words: ['cat', 'dog', 'and', 'cat', 'and', 'com', 'and', 'the']
Words that start with c and end with t: ['cat', 'cat']
Version numbers: ['v1.3', 'v12.10']
Emails: ['hello123@test.com', 'admin@service.io']
Uppercase + digits: ['B12']
cat or dog: ['cat', 'dog', 'cat']
Hyphenated words: ['robot-42']